import Foundation

enum TranscriptFormatter {

    static func renderMarkdown(_ doc: TranscriptDocument) -> String {
        let isoDate = ISO8601DateFormatter().string(from: doc.date)
        var speakersYaml = ""
        for s in doc.speakers {
            speakersYaml += "  - { id: \(s.id), name: \"\(escape(s.name))\" }\n"
        }

        var attendeesYaml = ""
        if let attendees = doc.attendees, !attendees.isEmpty {
            let list = attendees.map { "\"\(escape($0))\"" }.joined(separator: ", ")
            attendeesYaml = "attendees: [\(list)]\n"
        }

        var out = """
        ---
        id: \(doc.id)
        title: \(escape(doc.title))
        date: \(isoDate)
        duration: \(formatDuration(doc.duration))
        language: \(doc.language.rawValue)
        model: \(doc.modelShortName)
        source_kind: \(doc.sourceKind.rawValue)
        \(doc.sourceURL.map { "source: \"\(escape($0))\"\n" } ?? "")\(attendeesYaml)speakers:
        \(speakersYaml)---

        # \(doc.title)

        """

        if let summary = doc.summary?.trimmingCharacters(in: .whitespacesAndNewlines),
           !summary.isEmpty {
            out += "\n## Summary\n\n\(summary)\n"
            if let model = doc.summaryModelShortName {
                out += "\n_Generated by \(model)._\n"
            }
        }

        out += "\n## Transcript\n\n"
        for seg in doc.segments {
            let time = formatTimestamp(seg.start)
            let name = doc.speakers.first(where: { $0.id == seg.speakerId })?.name ?? "Unknown"
            out += "[\(time)] **\(name)**: \(seg.text)\n\n"
        }

        return out
    }

    /// Speaker-labelled plain text suitable for feeding to an LLM.
    /// Timestamps are dropped — they only waste tokens for summarization.
    static func renderPlainForLLM(_ doc: TranscriptDocument) -> String {
        var out = ""
        for seg in doc.segments {
            let name = doc.speakers.first(where: { $0.id == seg.speakerId })?.name ?? "Speaker"
            out += "\(name): \(seg.text)\n"
        }
        return out
    }

    /// Self-contained Markdown block for just the summary, titled with the
    /// meeting name so the paste is useful on its own. Returns nil if the
    /// transcript has no summary yet.
    static func renderSummaryMarkdown(_ doc: TranscriptDocument) -> String? {
        guard let summary = doc.summary?.trimmingCharacters(in: .whitespacesAndNewlines),
              !summary.isEmpty else { return nil }

        var out = "# \(doc.title)\n\n"
        out += "## Summary\n\n\(summary)\n\n"
        if let model = doc.summaryModelShortName {
            out += "_Generated by \(model)._\n"
        }
        return out
    }

    private static func escape(_ s: String) -> String {
        s.replacingOccurrences(of: "\"", with: "\\\"")
    }

    private static func formatTimestamp(_ s: Double) -> String {
        let t = Int(s)
        let h = t / 3600, m = (t % 3600) / 60, sec = t % 60
        return h > 0
            ? String(format: "%d:%02d:%02d", h, m, sec)
            : String(format: "%d:%02d", m, sec)
    }

    private static func formatDuration(_ s: TimeInterval) -> String {
        let t = Int(s)
        let h = t / 3600, m = (t % 3600) / 60, sec = t % 60
        return String(format: "%02d:%02d:%02d", h, m, sec)
    }
}
